const CHANGE_LABEL = 'CHANGE_QUESTION_LABEL';
const CHANGE_TYPE = 'CHANGE_QUESTION_TYPE';
const CHANGE_DESCRIPTION = 'CHANGE_QUESTION_DESCRIPTION';
const CHANGE_OPTION = 'CHANGE_QUESTION_OPTION';
const ADD_OPTION = 'ADD_QUESTION_OPTION';


export default {
  CHANGE_LABEL,
  CHANGE_TYPE,
  CHANGE_DESCRIPTION,
  ADD_OPTION,
  CHANGE_OPTION,
};
