const CHANGE_LABEL = 'CHANGE_QUESTION_LABEL';
const CHANGE_TYPE = 'CHANGE_QUESTION_TYPE';
const CHANGE_DESCRIPTION = 'CHANGE_QUESTION_DESCRIPTION';
const CHANGE_OPTIONS = 'CHANGE_QUESTION_OPTIONS';


export default {
  CHANGE_LABEL,
  CHANGE_TYPE,
  CHANGE_DESCRIPTION,
  CHANGE_OPTIONS,
};
